{
  rewindTest(new Callable<Integer>(){
    public Integer call(){
      return 0;
    }
  }
,new Runnable(){
    public void run(){
      try {
        new DynamicWind().unwindTest(new Callable<Integer>(){
          public Integer call(){
            continuationReference.handleResult(1);
            throw new AssertionError();
          }
        }
);
      }
 catch (      Exception e) {
        throw new RuntimeException(e);
      }
    }
  }
);
}
