{
  before.run();
  if (exception != null) {
    continuation.handleException(exception);
  }
 else {
    continuation.handleResult(result);
  }
  throw new AssertionError();
}
