{
  rewindTest(new Callable<Integer>(){
    public Integer call() throws Exception {
      throw new MyException(0);
    }
  }
,new Runnable(){
    public void run(){
      try {
        new DynamicWind().unwindTest(new Callable<Integer>(){
          public Integer call(){
            continuationReference.handleException(new MyException(1));
            throw new AssertionError();
          }
        }
);
      }
 catch (      Exception e) {
        throw new RuntimeException(e);
      }
    }
  }
);
}
